### ISSUE TITLE
Error while using price importer

### ISSUE THREAD

**Issue by VasumathiJayakumar** [commercetools/csv-parser-price#29]
### Description

Getting error with status 400 while using price importer in impex

`{ statusCode: 400,
message: 'Malformed parameter: where: Syntax error while parsing \'where\'. Invalid input \',\', expected StringLiteral, NumberLiteral, boolean or inputParam (line 1, column 23):\nmasterVariant(sku in (,,)) or variants(sku in (,,))\n ^',
errors: 
[
{ code: 'InvalidInput', message: 'Malformed parameter: where: Syntax error while parsing \'where\'. Invalid input \',\', expected StringLiteral, NumberLiteral, boolean or inputParam (line 1, column 23):\nmasterVariant(sku in (,,)) or variants(sku in (,,))\n ^' }
],
originalRequest: 
{ endpoint: '/product-projections?where=masterVariant(sku%20in%20(%2C%2C))%20or%20variants(sku%20in%20(%2C%2C))&sort=id%20asc&staged=true',
options: 
{ config:
{ project_key: 'csv-connector-test-30' }
,
host: 'api.sphere.io',
protocol: 'https',
timeout: 20000,
rejectUnauthorized: true,
headers: 
{ 'User-Agent': 'sphere-node-cli - 0.9.0', Authorization: 'Bearer hVcQxfIOtaqJp8zM3jCy03dFIufEIR_E' }
,
uri: 'https://api.sphere.io/csv-connector-test-30',
gzipEnable: true } } }
Process exited with code (1)`

**Comment by hisabimbola** [comment]
This repo has been deprecated, and you issue created [here](https://github.com/commercetools/nodejs/issues/156)
